config/routes.rb
Rails.application.routes.draw do
  namespace :wizards do
    namespace :leagues do
      get 'leagues/new'
    end
  end

  namespace :wizards do
    namespace :leagues do
      get 'leagues/create'
    end
  end

  devise_for :users

  root to: 'home#index'

  namespace :admin do
    resources :games
    resources :averages
    resources :teams
    resources :matches
    resources :weeks
    resources :leagues
    resources :seasons
    resources :users
    get '/', to: 'dashboard#show'
  end

  namespace :wizards do
    namespace :leagues do
      resources :leagues, only: [:new, :create]
      resources :seasons, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  resources :leagues
  resources :averages
  resources :teams
  resources :matches
  resources :weeks
  resources :leagues
  resources :seasons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :week
  belongs_to :left_team, class_name: 'Team'
  belongs_to :right_team, class_name: 'Team'
  has_many :games

  delegate :season, to: :week

  def teams
    left_team + right_team
  end
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < Admin::ApplicationController
  before_action :set_admin_match, only: [:show, :edit, :update, :destroy]

  # GET /admin/matches
  # GET /admin/matches.json
  def index
    @admin_matches = Match.order(:id).page params[:page]
  end

  # GET /admin/matches/1
  # GET /admin/matches/1.json
  def show
  end

  # GET /admin/matches/new
  def new
    @admin_match = Match.new
  end

  # GET /admin/matches/1/edit
  def edit
  end

  # POST /admin/matches
  # POST /admin/matches.json
  def create
    @admin_match = Match.new(admin_match_params)

    respond_to do |format|
      if @admin_match.save
        format.html { redirect_to @admin_match, success: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @admin_match }
      else
        format.html { render :new }
        format.json { render json: @admin_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/matches/1
  # PATCH/PUT /admin/matches/1.json
  def update
    respond_to do |format|
      if @admin_match.update(admin_match_params)
        format.html { redirect_to @admin_match, success: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_match }
      else
        format.html { render :edit }
        format.json { render json: @admin_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/matches/1
  # DELETE /admin/matches/1.json
  def destroy
    @admin_match.destroy
    respond_to do |format|
      format.html { redirect_to admin_matches_url, success: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_match
      @admin_match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_match_params
      params.fetch(:admin_match, {})
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:left_team, :right_team, :left_lane, :right_lane, :left_payment, :right_payment, :left_points_on, :right_points_won, :week_id)
    end
end

app/helpers/admin/matches_helper.rb
module Admin::MatchesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

end

app/views/admin/matches/_destroy_modal.html.haml
#delete-confirm.modal.fade
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header.panel-title
        Destroy Confirmation
        %button.close{'data-dismiss'=>'modal'}
          %span.glyphicon.glyphicon-remove
      .modal-body
        Are you sure you want to destroy this match
        %strong
          {{name}}
        and all games of that match? This action is permanent and cannot be undone.
      .modal-footer
        = link_to 'matches/{{id}}', { class: 'btn btn-danger', :method => :delete } do
          %span.glyphicon.glyphicon-trash
          Destroy
        %button.btn.btn-default{'data-dismiss' => 'modal'}
          Cancel

app/views/admin/matches/_form.html.haml
- if @admin_match.errors.any?
  #error_explanation
    %h2= "#{pluralize(@admin_match.errors.count, "error")} prohibited this Match from being saved:"
    %ul
      - @admin_match.errors.full_messages.each do |msg|
        %li= msg
.form-group.row
  .col-sm-3
    = f.label :left_lane
  .col-sm-6
    = f.select :left_lane, options_for_select((1..48),(1..48)), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :right_lane
  .col-sm-6
    = f.select :right_lane, options_for_select((1..48),(1..48)), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :left_team
  .col-sm-6
    = f.select :left_team, options_for_select([],[]), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :right_team
  .col-sm-6
    = f.select :right_team, options_for_select([],[]), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :right_team_dues
  .col-sm-6
    = f.text_field :right_team_dues, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :left_team_dues
  .col-sm-6
    = f.text_field :left_team_dues, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :right_points_won
  .col-sm-6
    = f.text_field :right_points_won, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :left_points_won
  .col-sm-6
    = f.text_field :left_team_dues, class: 'form-control'

app/views/admin/matches/_table.html.haml
.table-responsive
  %table#matches_table.table.table-bordered.table-hover
    %thead
      %tr
        %th Season
        %th Week
        %th Left Lane
        %th Left Team
        %th Left Team Dues
        %th Left Team Points Won
        %th Right Lane
        %th Right Team
        %th Right Team Dues
        %th Right Team Points Won
        %th Actions

    %tbody
      - @admin_matches.each do |match|
        %tr
          %td= match.season.full_name
          %td= match.week.number
          %td= match.left_lane
          %td= match.left_team.name
          %td= match.left_team_dues
          %td= match.left_points_won
          %td= match.right_lane
          %td= match.right_team.name
          %td= match.right_team_dues
          %td= match.right_points_won
          %td
            .btn-group
              = link_to 'Show', admin_match_path(match), {class: 'btn btn-primary btn-sm'}
              = link_to 'Edit', edit_admin_match_path(match), {class: 'btn btn-info btn-sm'}
              = link_to 'Destroy', '#delete-confirm', {class: 'delete-confirm btn btn-danger btn-sm', 'data-id' => match.id, 'data-name' => "#{match.id}" }
= paginate @admin_matches, :window => 2
= render 'destroy_modal'

app/views/admin/matches/edit.html.haml
.page-header
  %h2 Edit Match

= simple_form_for @admin_match, url: { controller: 'matches', action: "update" }, html: {class: 'form-vertical', method: :patch} do |f|

  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          = "Match #{@admin_match.id}"
    .panel-body
      = render 'form', f: f
  .actions
    = button_tag type: 'submit', class: 'btn btn-success' do
      %span.glyphicon.glyphicon-edit
      Save
    = link_to 'Cancel', admin_matches_path, class: 'btn btn-default'

app/views/admin/matches/index.html.haml
.page-header
  = link_to 'New Match', new_admin_match_path, class: 'btn btn-success pull-right'
  %h2 Matches
%br
= render 'table'

app/views/admin/matches/new.html.haml
%h1 New admin_match

= render 'form'

= link_to 'Back', admin_matches_path

app/views/admin/matches/show.html.haml
.row#notice= notice

.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = "Match #{@admin_match.id}"
      .panel-body
        .row
          .col-sm-3
            %label
              Week
          .col-sm-9
            = link_to @admin_match.week.number, admin_week_path(@admin_match.week)
        .row
          .col-sm-3
            %label
              Left Lane
          .col-sm-9
            = @admin_match.left_lane
        .row
          .col-sm-3
            %label
              Left Team
          .col-sm-9
            = @admin_match.left_team.name
        .row
          .col-sm-3
            %label
              Left Dues
          .col-sm-9
            = @admin_match.left_team_dues
        .row
          .col-sm-3
            %label
              Left Points Won
          .col-sm-9
            = @admin_match.left_points_won
        .row
          .col-sm-3
            %label
              Right Lane
          .col-sm-9
            = @admin_match.right_lane
        .row
          .col-sm-3
            %label
              Right Team
          .col-sm-9
            = @admin_match.right_team.name
        .row
          .col-sm-3
            %label
              Right Dues
          .col-sm-9
            = @admin_match.right_team_dues
        .row
          .col-sm-3
            %label
              Right Points Won
          .col-sm-9
            = @admin_match.right_points_won
= link_to 'Edit', edit_admin_match_path(@admin_match), class: 'btn btn-info'
= link_to 'Back', admin_matches_path, class: 'btn btn-default'