config/routes.rb
Rails.application.routes.draw do
  namespace :wizards do
    namespace :leagues do
      get 'leagues/new'
    end
  end

  namespace :wizards do
    namespace :leagues do
      get 'leagues/create'
    end
  end

  devise_for :users

  root to: 'home#index'

  namespace :admin do
    resources :games
    resources :averages
    resources :teams
    resources :matches
    resources :weeks
    resources :leagues
    resources :seasons
    resources :users
    get '/', to: 'dashboard#show'
  end

  namespace :wizards do
    namespace :leagues do
      resources :leagues, only: [:new, :create]
      resources :seasons, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  resources :leagues
  resources :averages
  resources :teams
  resources :matches
  resources :weeks
  resources :leagues
  resources :seasons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :match
  belongs_to :member, foreign_key: :member_id, class_name: 'User'
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::ApplicationController
  before_action :set_admin_game, only: [:show, :edit, :update, :destroy]

  # GET /admin/games
  # GET /admin/games.json
  def index
    @admin_games = Game.order(:id).page params[:page]
  end

  # GET /admin/games/1
  # GET /admin/games/1.json
  def show
  end

  # GET /admin/games/new
  def new
    @admin_game = Game.new
  end

  # GET /admin/games/1/edit
  def edit
  end

  # POST /admin/games
  # POST /admin/games.json
  def create
    @admin_game = Game.new(admin_game_params)

    respond_to do |format|
      if @admin_game.save
        format.html { redirect_to @admin_game, success: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @admin_game }
      else
        format.html { render :new }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/games/1
  # PATCH/PUT /admin/games/1.json
  def update
    respond_to do |format|
      if @admin_game.update(admin_game_params)
        format.html { redirect_to @admin_game, success: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_game }
      else
        format.html { render :edit }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/games/1
  # DELETE /admin/games/1.json
  def destroy
    @admin_game.destroy
    respond_to do |format|
      format.html { redirect_to admin_games_url, success: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_game
      @admin_game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_game_params
      params.fetch(:admin_game, {})
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:match_id, :score, :performed_date)
    end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_destroy_modal.html.haml
#delete-confirm.modal.fade
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header.panel-title
        Destroy Confirmation
        %button.close{'data-dismiss'=>'modal'}
          %span.glyphicon.glyphicon-remove
      .modal-body
        Are you sure you want to destroy the game
        %strong
          {{name}}
        ? This action is permanent and cannot be undone.
      .modal-footer
        = link_to 'games/{{id}}', { class: 'btn btn-danger', :method => :delete } do
          %span.glyphicon.glyphicon-trash
          Destroy
        %button.btn.btn-default{'data-dismiss' => 'modal'}
          Cancel

app/views/admin/games/_form.html.haml
- if @admin_game.errors.any?
  #error_explanation
    %h2= "#{pluralize(@admin_game.errors.count, "error")} prohibited this Game from being saved:"
    %ul
      - @admin_game.errors.full_messages.each do |msg|
        %li= msg

.form-group.row
  .col-sm-3
    = f.label :match_id, text: 'Match'
  .col-sm-6
    = f.select :match_id, options_for_select([[],[]], nil), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :member_id, text: 'Starting Year'
  .col-sm-6
    = f.select :member_id, options_for_select(user_picker_values, selected_user), {}, {class: 'selectpicker', 'data-width' => '100%'}
.form-group.row
  .col-sm-3
    = f.label :scratch_total
  .col-sm-6
    = f.text_field :scratch_total, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :handicap
  .col-sm-6
    = f.text_field :handicap, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :total_score
  .col-sm-6
    = f.text_field :total_score, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :game_number
  .col-sm-6
    = f.text_field :game_number, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :game_position
  .col-sm-6
    = f.text_field :game_position, class: 'form-control'
.form-group.row
  .col-sm-3
    = f.label :performed_date
  .col-sm-6
    = f.text_field :performed_date, {class: 'datepicker form-control'}

app/views/admin/games/_table.html.haml
.table-responsive
  %table#games_table.table.table-bordered.table-hover
    %thead
      %tr
        %th Match
        %th Bowler
        %th Total
        %th Actions

    %tbody
      - @admin_games.each do |game|

        %tr
          %td= game.match_id
          %td= game.member.full_name
          %td= game.total_score
          %td
            .btn-group
              = link_to 'Show', admin_game_path(game), {class: 'btn btn-primary btn-sm'}
              = link_to 'Edit', edit_admin_game_path(game), {class: 'btn btn-info btn-sm'}
              = link_to 'Destroy', '#delete-confirm', {class: 'delete-confirm btn btn-danger btn-sm', 'data-id' => game.id, 'data-name' => "ID: #{game.id}" }
= paginate @admin_games, :window => 2
= render 'destroy_modal'

app/views/admin/games/edit.html.haml
.page-header
  %h2 Edit Game

= simple_form_for @admin_game, url: { controller: 'games', action: "update" }, html: {class: 'form-vertical', method: :patch} do |f|

  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          = "Game #{@admin_game.id}"
    .panel-body
      = render 'form', f: f
  .actions
    = button_tag type: 'submit', class: 'btn btn-success' do
      %span.glyphicon.glyphicon-edit
      Save
    = link_to 'Cancel', admin_games_path, class: 'btn btn-default'

app/views/admin/games/index.html.haml
.page-header
  = link_to 'New Games', new_admin_game_path, class: 'btn btn-success pull-right'
  %h2 Games
%br
= render 'table'

app/views/admin/games/new.html.haml
.page-header
  %h2 New Game
= simple_form_for @admin_game, url: { controller: 'games', action: "create" }, html: {class: 'form-vertical'} do |f|

  .panel.panel-default
    .panel-body
      = render 'form', f: f
  .actions
    = button_tag type: 'submit', class: 'btn btn-success' do
      %span.glyphicon.glyphicon-edit
      Save
    = link_to 'Cancel', admin_games_path, class: 'btn btn-default'

app/views/admin/games/show.html.haml
%p#notice= notice

.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = "Game #{@admin_game.id}"
      .panel-body
        .row
          .col-sm-3
            %label
              Match
          .col-sm-6
            = link_to @admin_game.match.id, admin_match_path(@admin_game.match)
        .row
          .col-sm-3
            %label
              Bowler
          .col-sm-6
            = link_to @admin_game.member.full_name, admin_user_path(@admin_game.member)

        .row
          .col-sm-3
            %label
              Scratch Total
          .col-sm-6
            = @admin_game.scratch_total

        .row
          .col-sm-3
            %label
              Handicap
          .col-sm-6
            = @admin_game.handicap
        .row
          .col-sm-3
            %label
              Game Total
          .col-sm-6
            = @admin_game.total_score
        .row
          .col-sm-3
            %label
              Game Number
          .col-sm-6
            = @admin_game.game_number
        .row
          .col-sm-3
            %label
              Game Position
          .col-sm-6
            = @admin_game.game_position
        .row
          .col-sm-3
            %label
              Date
          .col-sm-6
            = date_format(@admin_game.performed_date)

= link_to 'Edit', edit_admin_game_path(@admin_game), class: 'btn btn-info'
= link_to 'Back', admin_games_path, class: 'btn btn-default'