config/routes.rb
Rails.application.routes.draw do
  namespace :wizards do
    namespace :leagues do
      get 'leagues/new'
    end
  end

  namespace :wizards do
    namespace :leagues do
      get 'leagues/create'
    end
  end

  devise_for :users

  root to: 'home#index'

  namespace :admin do
    resources :games
    resources :averages
    resources :teams
    resources :matches
    resources :weeks
    resources :leagues
    resources :seasons
    resources :users
    get '/', to: 'dashboard#show'
  end

  namespace :wizards do
    namespace :leagues do
      resources :leagues, only: [:new, :create]
      resources :seasons, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  resources :leagues
  resources :averages
  resources :teams
  resources :matches
  resources :weeks
  resources :leagues
  resources :seasons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/week.rb
class Week < ApplicationRecord
  belongs_to :season
  has_many :matches, dependent: :destroy
end

app/controllers/admin/weeks_controller.rb
class Admin::WeeksController < Admin::ApplicationController
  before_action :set_admin_week, only: [:show, :edit, :update, :destroy]

  # GET /admin/weeks
  # GET /admin/weeks.json
  def index
    @admin_weeks = Week.order(:id).page params[:page]
  end

  # GET /admin/weeks/1
  # GET /admin/weeks/1.json
  def show
  end

  # GET /admin/weeks/new
  def new
    @admin_week = Week.new
  end

  # GET /admin/weeks/1/edit
  def edit
  end

  # POST /admin/weeks
  # POST /admin/weeks.json
  def create
    @admin_week = Week.new(admin_week_params)

    respond_to do |format|
      if @admin_week.save
        format.html { redirect_to @admin_week, success: 'Week was successfully created.' }
        format.json { render :show, status: :created, location: @admin_week }
      else
        format.html { render :new }
        format.json { render json: @admin_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/weeks/1
  # PATCH/PUT /admin/weeks/1.json
  def update
    respond_to do |format|
      if @admin_week.update(admin_week_params)
        format.html { redirect_to @admin_week, success: 'Week was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_week }
      else
        format.html { render :edit }
        format.json { render json: @admin_week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/weeks/1
  # DELETE /admin/weeks/1.json
  def destroy
    @admin_week.destroy
    respond_to do |format|
      format.html { redirect_to admin_weeks_url, success: 'Week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_week
      @admin_week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_week_params
      params.fetch(:admin_week, {})
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :edit, :update, :destroy]

  # GET /weeks
  # GET /weeks.json
  def index
    @weeks = Week.all
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
  end

  # GET /weeks/new
  def new
    @week = Week.new
  end

  # GET /weeks/1/edit
  def edit
  end

  # POST /weeks
  # POST /weeks.json
  def create
    @week = Week.new(week_params)

    respond_to do |format|
      if @week.save
        format.html { redirect_to @week, notice: 'Week was successfully created.' }
        format.json { render :show, status: :created, location: @week }
      else
        format.html { render :new }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weeks/1
  # PATCH/PUT /weeks/1.json
  def update
    respond_to do |format|
      if @week.update(week_params)
        format.html { redirect_to @week, notice: 'Week was successfully updated.' }
        format.json { render :show, status: :ok, location: @week }
      else
        format.html { render :edit }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week.destroy
    respond_to do |format|
      format.html { redirect_to weeks_url, notice: 'Week was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_week
      @week = Week.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def week_params
      params.require(:week).permit(:date, :sequence, :season_id)
    end
end

app/helpers/admin/weeks_helper.rb
module Admin::WeeksHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/admin/weeks/_destroy_modal.html.haml
#delete-confirm.modal.fade
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header.panel-title
        Destroy Confirmation
        %button.close{'data-dismiss'=>'modal'}
          %span.glyphicon.glyphicon-remove
      .modal-body
        Are you sure you want to destroy the week
        %strong
          {{name}}
        and all matches and games of that week? This action is permanent and cannot be undone.
      .modal-footer
        = link_to 'weeks/{{id}}', { class: 'btn btn-danger', :method => :delete } do
          %span.glyphicon.glyphicon-trash
          Destroy
        %button.btn.btn-default{'data-dismiss' => 'modal'}
          Cancel

app/views/admin/weeks/_form.html.haml
- if @admin_week.errors.any?
  #error_explanation
    %h2= "#{pluralize(@admin_week.errors.count, "error")} prohibited this Week from being saved:"
    %ul
      - @admin_week.errors.full_messages.each do |msg|
        %li= msg

.form-group.row
  .col-sm-3
    = f.label :number
  .col-sm-6
    = f.select :number, options_for_select((1..40),(1..40)), {}, {class: 'selectpicker', 'data-width' => '100%'}

.form-group.row
  .col-sm-3
    = f.label :season
  .col-sm-6
    = f.select :season, options_for_select(Season.all.order(:id).map(&:full_name), Season.all.order(:id).map(&:id)), {}, {class: 'selectpicker', 'data-width' => '100%'}

.form-group.row
  .col-sm-3
    = f.label :date
  .col-sm-6
    = f.text_field :date, {class: 'datepicker form-control'}

app/views/admin/weeks/_table.html.haml
.table-responsive
  %table#weeks_table.table.table-bordered.table-hover
    %thead
      %tr
        %th Season
        %th Number
        %th Date
        %th Actions
    %tbody
      - @admin_weeks.each do |week|
        %tr
          %td
            = "#{week.season.league.name} #{week.season.year}"
          %td
            = week.number
          %td
            = day_week_month(week.date)
          %td
            .btn-group
              = link_to 'Show', admin_week_path(week), {class: 'btn btn-primary btn-sm'}
              = link_to 'Edit', edit_admin_week_path(week), {class: 'btn btn-info btn-sm'}
              = link_to 'Destroy', '#delete-confirm', {class: 'delete-confirm btn btn-danger btn-sm', 'data-id' => week.id, 'data-name' => "#{week.number} of #{week.season.full_name}" }
= paginate @admin_weeks, :window => 2
= render 'destroy_modal'

app/views/admin/weeks/edit.html.haml
.page-header
  %h2 Edit Week

= simple_form_for @admin_week, url: { controller: 'weeks', action: "update" }, html: {class: 'form-vertical', method: :patch} do |f|

  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          = "Week #{@admin_week.id}"
    .panel-body
      = render 'form', f: f
  .actions
    = button_tag type: 'submit', class: 'btn btn-success' do
      %span.glyphicon.glyphicon-edit
      Save
    = link_to 'Cancel', admin_weeks_path, class: 'btn btn-default'

app/views/admin/weeks/index.html.haml
.page-header
  = link_to 'New Week', new_admin_week_path, class: 'btn btn-success pull-right'
  %h2 Weeks
%br
= render 'table'

app/views/admin/weeks/new.html.haml
.page-header
  %h2 New week
= simple_form_for @admin_week, url: { controller: 'weeks', action: "create" }, html: {class: 'form-vertical'} do |f|

  .panel.panel-default
    .panel-body
      = render 'form', f: f
  .actions
    = button_tag type: 'submit', class: 'btn btn-success' do
      %span.glyphicon.glyphicon-edit
      Save
    = link_to 'Cancel', admin_weeks_path, class: 'btn btn-default'

app/views/admin/weeks/show.html.haml
%p#notice= notice

.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = "Week #{@admin_week.id}"
      .panel-body
        .row
          .col-sm-3
            %label
              Season
          .col-sm-6
            = @admin_week.season.full_name
        .row
          .col-sm-3
            %label
              Number
          .col-sm-6
            = @admin_week.number
        .row
          .col-sm-3
            %label
              Date
          .col-sm-6
            = date_format(@admin_week.date)

= link_to 'Edit', edit_admin_week_path(@admin_week), class: 'btn btn-info'
= link_to 'Back', admin_weeks_path, class: 'btn btn-default'